---
- name: read secret
  hosts: all
  serial: 1
  become: true

  vars:
    VAULT_ADDR: ""
    VAULT_TOKEN: ""
    VAULT_NAMESPACE: ""
    some_secret: "{{ lookup('hashi_vault', 'secret=secret/data/test token={{ VAULT_TOKEN }} url={{ VAULT_ADDR }} namespace={{ VAULT_NAMESPACE }}') }}"

  tasks:

  - name: install common packages
    yum:
      name:
        - unzip
        - vim
        - jq
      state: present

  - debug:
      msg: "The secret is {{ some_secret }}"