---
- name: test remote exec
  hosts: all
  serial: 1
  become: true

  vars:
    VAULT_ADDR: ""
    VAULT_NAMESPACE: ""
    ANSIBLE_ROLE_ID: ""
    ANSIBLE_SECRET_ID: ""

  tasks:

  - name: Retrieve wrapped secret id
    community.hashi_vault.vault_write:
      url: "{{ VAULT_ADDR }}"
      validate_certs: False
      namespace: "{{ VAULT_NAMESPACE }}"
      auth_method: approle
      role_id: "{{ ANSIBLE_ROLE_ID }}"
      secret_id: "{{ ANSIBLE_SECRET_ID }}"
      path: 'auth/approle/role/app1/secret-id' 
      wrap_ttl: 10m
    register: wrapped_secret_id

  - debug:
      msg: "The wrapped secret id {{ wrapped_secret_id.data.wrap_info.token }}"

  - copy:
      content: "{{ wrapped_secret_id.data.wrap_info.token }}"
      dest: "/home/rocky/templates/secretid_wrapped"