---
- name: read secret
  hosts: all
  serial: 1
  become: true

  vars:
    VAULT_ADDR: ""
    VAULT_TOKEN: ""
    VAULT_NAMESPACE: ""

  tasks:

  - name: Retrieve secret
    community.hashi_vault.vault_read:
      url: "{{ VAULT_ADDR }}"
      validate_certs: False
      namespace: "{{ VAULT_NAMESPACE }}"
      token: "{{ VAULT_TOKEN }}"
      path: "secret/data/test" 
    register: some_secret

  - debug:
      msg: "The secret is {{ some_secret.data.data }}"