---
- name: read secret
  hosts: all
  serial: 1
  become: true

  vars:
    VAULT_ADDR: ""
    VAULT_NAMESPACE: ""
    some_secret: "{{ lookup('hashi_vault', 'secret=secret/data/test auth_method=aws_iam role_id=jrx-test-ansible-role profile=jrx--ansible-instance-profile url={{ VAULT_ADDR }} namespace={{ VAULT_NAMESPACE }} validate_certs=False') }}"

  tasks:

  - debug:
      msg: "The secret is {{ some_secret }}"