---
- name: Install pre-requisites
  ansible.builtin.import_playbook: test.yml

- name: Vault Agent
  hosts: all
  serial: 1
  become: true

  vars:
    VAULT_ADDR: ""
    VAULT_NAMESPACE: ""

  tasks:

    - name: Ensure vault user exists
      user:
        name: vault
        system: yes
        group: vault

    - name: Ensure Vault configuration directory exists
      file:
        path: /etc/vault.d
        state: directory
        owner: vault
        group: vault
        mode: '0750'

    - name: Transfer Configuration File
      template:
        src: ./files/vault-agent.hcl.j2
        dest: /etc/vault.d/agent.hcl
        mode: 0640
        owner: vault
        group: vault

    - name: Transfer Secret Template File
      copy:
        src: ./files/secret.tpl
        dest: /etc/vault.d/secret.tpl
        mode: 0640
        owner: vault
        group: vault

    - name: Transfer CA Template File
      copy:
        src: ./files/ca.tpl
        dest: /etc/vault.d/ca.tpl
        mode: 0640
        owner: vault
        group: vault

    - name: Transfer Certificate Template File
      copy:
        src: ./files/certificate.tpl
        dest: /etc/vault.d/certificate.tpl
        mode: 0640
        owner: vault
        group: vault

    - name: Transfer Key Template File
      copy:
        src: ./files/key.tpl
        dest: /etc/vault.d/key.tpl
        mode: 0640
        owner: vault
        group: vault

    - name: Transfer Service File
      copy:
        src: vault-agent.service
        dest: /etc/systemd/system/vault-agent.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd to recognize Vault Agent service
      systemd:
        daemon_reload: yes

    - name: Enable Vault Agent service
      systemd:
        name: vault-agent.service
        enabled: yes

    - name: Start Vault Agent service
      systemd:
        name: vault-agent.service
        state: restarted