---
- name: test remote exec
  hosts: all
  serial: 1
  become: true

  vars:
    VAULT_ADDR: ""
    VAULT_NAMESPACE: ""

  tasks:

  - name: Retrieve wrapped secret id
    community.hashi_vault.vault_write:
      url: "{{ VAULT_ADDR }}"
      validate_certs: False
      namespace: "{{ VAULT_NAMESPACE }}"
      auth_method: approle
      role_id: "08817793-7de2-d4e6-e792-8a426b693412"
      secret_id: "b56c11f3-3cba-9ca0-f68d-21ec4e75eeba"
      path: 'auth/approle/role/app1/secret-id' 
      wrap_ttl: 10m
    register: wrapped_secret_id

  - debug:
      msg: "The wrapped secret id {{ wrapped_secret_id.data.wrap_info.token }}"

  - copy:
      content: "{{ wrapped_secret_id.data.wrap_info.token }}"
      dest: "/home/rocky/templates/secretid_wrapped"